
<!-- required content -->

<link rel="stylesheet" href="/css/nodedocs.css" type="text/css" media="screen" title="no title" charset="utf-8">
<link rel="stylesheet" href="/css/highlight/github.css" type="text/css" media="screen" title="no title" charset="utf-8">


<header>
  <div class="github title"><a href="http://github.com/nodejitsu/docs">Edit this page on GitHub</a></div>
  <div class="title"><a href="http://docs.nodejitsu.com">docs.nodejitsu.com</a></div>
</header>


<script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>

<script type="text/javascript" charset="utf-8" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

<div id="mask"></div>

<!-- end required content -->

<!-- <div id="toc"></div> -->

<!-- generated content -->
<div id="article">
  <div id="metadata">
    <h1 class="title">What is try-catch?</h1>
    <div class="date">Fri Aug 26 2011 03:08:50 GMT-0700 (PST)</div>
    <div class="author">nico</div>
    <!--
      <div class="tags"></div>
      <div class="difficulty"></div>
    -->
  </div>
  <div id="content"><p>Example:</p>

<pre><code>console.log(&quot;entering <span class="keyword">try</span>-<span class="keyword">catch</span> statement&quot;);

<span class="keyword">try</span> {
  console.log(&quot;entering <span class="keyword">try</span> block&quot;);
  <span class="keyword">throw</span> &quot;<span class="keyword">throw</span>n message&quot;;
  console.log(&quot;<span class="keyword">this</span> message is never seen&quot;);
}
<span class="keyword">catch</span> (e) {
  console.log(&quot;entering <span class="keyword">catch</span> block&quot;);
  console.log(e);
  console.log(&quot;leaving <span class="keyword">catch</span> block&quot;);
}
<span class="keyword">finally</span> {
  console.log(&quot;entering and leaving the <span class="keyword">finally</span> block&quot;);
}

console.log(&quot;leaving <span class="keyword">try</span>-<span class="keyword">catch</span> statement&quot;);</code></pre>

<p>Results:</p>

<pre><code>entering <span class="keyword">try</span>-<span class="keyword">catch</span> statement
entering <span class="keyword">try</span> block
entering <span class="keyword">catch</span> block
<span class="keyword">throw</span>n message
leaving <span class="keyword">catch</span> block
entering and leaving the <span class="keyword">finally</span> block
leaving <span class="keyword">try</span>-<span class="keyword">catch</span> statement</code></pre>

<p>Javascript's <code><span class="keyword">try</span>-<span class="keyword">catch</span>-<span class="keyword">finally</span></code> statement works very similarly to the <code><span class="keyword">try</span>-<span class="keyword">catch</span>-<span class="keyword">finally</span></code> encountered in C++ and Java.  First, the try block is executed until and unless the code in it throws an exception (whether it is an explicit <code><span class="keyword">throw</span></code> statement, the code has an uncaught native exception, or if the code calls a function that uses <code><span class="keyword">throw</span></code>). </p>

<p>If the code doesn't throw an exception, then the whole try block is executed. If the code threw an exception inside the try block, then the catch block is executed.  Last of all, the finally block is always executed, subsequent to the other blocks but prior to any subsequent code located outside of the <code><span class="keyword">try</span>-<span class="keyword">catch</span>-<span class="keyword">finally</span></code> blocks.  The <code><span class="keyword">finally</span></code> block will just about always execute, no matter what kind of throwing, catching, or returning one might be trying to do inside the <code><span class="keyword">try</span></code> or <code><span class="keyword">catch</span></code> blocks.</p>

<p>Note that you can omit the <code><span class="keyword">catch</span></code> or <code><span class="keyword">finally</span></code> block, but one of them must be present.</p>

<h2>But wait, isn't it Node.js convention to not use try-catch?</h2>

<p>In the core node.js libraries, the only place that one really <em>needs</em> to use a try-catch is around <code>JSON.parse()</code>. All of the other methods use either the standard Error object through the first parameter of the callback or emit an <code>error</code> event. Because of this, it is generally considered <a href="/what-are-the-error-conventions">standard</a> to return errors through the callback rather than to use the <code><span class="keyword">throw</span></code> statement. </p></div>
</div>

<!-- end generated content -->


<script type="text/javascript">
var _sf_async_config={uid:11119,domain:"docs.nodejitsu.com"};
(function(){
  function loadChartbeat() {
    window._sf_endpt=(new Date()).getTime();
    var e = document.createElement('script');
    e.setAttribute('language', 'javascript');
    e.setAttribute('type', 'text/javascript');
    e.setAttribute('src',
       (("https:" == document.location.protocol) ? "https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/" : "http://static.chartbeat.com/") +
       "js/chartbeat.js");
    document.body.appendChild(e);
  }
  var oldonload = window.onload;
  window.onload = (typeof window.onload != 'function') ?
     loadChartbeat : function() { oldonload(); loadChartbeat(); };
})();

</script>